/*
 * dio_cnfg.c
 *
 *  Created on: ??þ/??þ/????
 *      Author: COMPUTER SHOW
 */

#include "dio_cnfg.h"

DIO_cnfg_t DIO_cnfg_arr [NUM_OF_PINS] =
{
		{PORT_D,PIN2,OUTPUT,LOW,NA,INITIALIZED},
		{PORT_D,PIN3,OUTPUT,LOW,NA,INITIALIZED},
		{PORT_D,PIN6,OUTPUT,LOW,NA,INITIALIZED},
		{PORT_D,PIN7,OUTPUT,LOW,NA,INITIALIZED},
		{PORT_B,PIN0,OUTPUT,LOW,NA,INITIALIZED},
		{PORT_B,PIN1,OUTPUT,LOW,NA,INITIALIZED},
		{PORT_B,PIN2,OUTPUT,LOW,NA,INITIALIZED},
		{PORT_B,PIN3,OUTPUT,LOW,NA,INITIALIZED}
};
//{PORT_C,PIN0,INPUT,NA,PULLUP,INITIALIZED}
